services:
  minio:
    image: minio/minio:latest
    container_name: wcb_minio
    environment:
      - MINIO_ROOT_USER=miniouser
      - MINIO_ROOT_PASSWORD=miniopassword
      - MINIO_DOMAIN=storage
      - MINIO_REGION_NAME=us-east-1
      - MINIO_REGION=us-east-1
    ports:
      - 9001:9001
      - 9000:9000
    command: ["server", "/data", "--console-address", ":9001"]
    volumes:
      - minio_data:/data
    networks:
      - default

  postgres:
    image: postgres:16
    container_name: wcb_postgres
    environment:
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgres-password
      - POSTGRES_DB=wcb
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  minio_data:
  pg_data:

networks:
  default:
